#!/bin/bash

# You can call this script like this:
case $1 in
    up)
    xbacklight +5 > /dev/null;
    echo $light+5 > /tmp/xob_backlight
    ;;
    down)
    xbacklight -5 > /dev/null;
    echo $light-5 > /tmp/xob_backlight
    ;;
esac
