#!/bin/bash

# You can call this script like this:

function send_notification {
light=`xbacklight -get | cut -d"." -f1`
icon_name="/usr/share/icons/Faba/48x48/notifications/notification-display-brightness.svg"
bar=$(seq -s "─" $(($light/5)) | sed 's/[0-9]//g')
# Send the notification
dunstify "$light""     ""$bar" -a "changeBacklight" -i "$icon_name" -t 2000 -h string:synchronous:"$bar" -r 600
}

case $1 in
    up)
	xbacklight +5 > /dev/null
	send_notification
	;;
    down)
	xbacklight -5 > /dev/null
	send_notification
	;;
esac
