#!/bin/bash

capacity="$(cat /sys/class/power_supply/BAT0/capacity)"
state="$(cat /sys/class/power_supply/BAT0/status)"

if [[ $capacity -lt 15 ]]; then
    symbol=" "
elif [[ $capacity -lt 30 ]]; then
    symbol=" "
elif [[ $capacity -lt 60 ]]; then
    symbol=" "
elif [[ $capacity -lt 90 ]]; then
    symbol=" "
elif [[ $capacity -lt 100 ]]; then
    symbol=" "
elif [[ $capacity -eq 100 ]]; then
    symbol=""
fi
    # symbol="🔌"
if [[ $state == "Charging" ]]; then
    symbol=""
# else
    # symbol="🔋"
fi
echo -e "$symbol $capacity%"
