#!/bin/bash

case "$(echo -e "Shutdown\nRestart\nLogout\nSuspend\nLock" | dmenu \
    -nb "${COLOR_BACKGROUND:-#000000}" \
    -nf "${COLOR_DEFAULT:-#ffffff}" \
    -sf "${COLOR_HIGHLIGHT:-#ffffff}" \
    -sb "#2a2a2a" \
    -b -i -p \
    "Power:" -l 5)" in
        Shutdown) exec systemctl poweroff;;
        Restart) exec systemctl reboot;;
        Logout) pkill dwm;;
        Suspend) exec systemctl suspend;;
        Lock) exec systemctl --user start lock.target;;
esac
