#!/usr/bin/env bash

option=`echo -e "Alacritty\nbspwm\nsxhkd\ndunst\ni3\ni3blocks\nlf\nmpd\nncmpcpp\nNeovim\npolybar\nrofi\nsxiv\nZathura\nCompton\nZsh\nst" |  rofi -dmenu -i -p "Select" -config ~/.cache/wal/colors-rofi-dark.rasi -theme ~/.config/rofi/mytheme.rasi`
case $option in
  "Alacritty" )
    $TERMINAL -e nvim ~/.config/alacritty/alacritty.yml;;
  "bspwm" )
    $TERMINAL -e nvim ~/.config/bspwm/bspwmrc;;
  "sxhkd" )
    $TERMINAL -e nvim ~/.config/bspwm/sxhkdrc;;
  "dunst" )
    $TERMINAL -e nvim ~/.config/dunst/dunstrc;;
  "i3" )
    $TERMINAL -e nvim ~/.config/i3/config;;
  "i3blocks" )
    $TERMINAL -e nvim ~/.config/i3blocks/config;;
  "lf" )
    $TERMINAL -e nvim ~/.config/lf/lfrc;;
  "mdp" )
    $TERMINAL -e nvim ~/.config/mpd/mpd.conf;;
  "ncmpcpp" )
    $TERMINAL -e nvim ~/.config/ncmpcpp/config;;
  "Neovim" )
    $TERMINAL -e nvim ~/.config/nvim/init.vim;;
  "polybar" )
    $TERMINAL -e nvim ~/.config/polybar/config;;
  "rofi" )
    $TERMINAL -e nvim ~/.config/rofi/config;;
  "sxiv" )
    $TERMINAL -e nvim ~/.config/sxiv/exec/key-handler;;
  "Zathura" )
    $TERMINAL -e nvim ~/.config/zathura/zathurarc;;
  "Compton" )
    $TERMINAL -e nvim ~/.config/compton.conf;;
  "Zsh" )
    $TERMINAL -e nvim ~/.zshrc;;
  "St" )
    $TERMINAL -e nvim ~/myst/config.def.h;;
esac
