#!/usr/bin/env bash

option=`echo -e "Reboot\nShutdown\nLockscreen\nLogout" |  rofi -config ~/.cache/wal/colors-rofi-dark.rasi -theme ~/.config/rofi/mytheme.rasi -dmenu -i -p "Select"`
case $option in
  "Reboot" )
    sudo reboot;;
  "Shutdown" )
    sudo shutdown -h now;;
  "Logout" )
    i3-msg exit
    bspc quit;;
  "Lockscreen" )
    betterlockscreen -s dim
esac
