#!/usr/bin/env bash
set -e

mpd &
xrdb ~/.Xdefaults &
dunst &
urxvtd &
betterlockscreen -u ~/Pictures/Wallpapers &
nm-applet &
unclutter &
xset b off &
blueman-applet &
redshift -l 13.082680:80.270718 &
# feh --bg-fill ~/.config/wall.png &
setxkbmap -option caps:swapescape &
wallslide &
sxhkd &
compton &
(conky | while read LINE; do xsetroot -name "$LINE"; done) &
exec dwm
