#!/bin/bash

while [[ true ]]; do
    echo -e "+@fg=1; $(xbacklight -get | cut -d"." -f1)%  +@fg=2; $(volume)  +@fg=3; $(battery)  +@fg=4;  $(TZ='Asia/Kolkata' date "+%a %d %b %I:%M %p %Y") +@fg=5; "
    sleep 1
done 
#
