#!/bin/bash
set -e

x=`amixer sget Master | tail -n 1 | tr -d "[]" | cut -d" " -f6 | tr -d "%"`

if [[ `amixer sget Master | grep off` ]]; then
  printf "🔇\\n" && exit
elif [ $x -gt "60" ]; then
	icon="🔊 "
elif [[ $x -gt "40" ]]; then
	icon="🔉 "
else
	icon="🔈 "
fi

echo "$icon$x%"
