#!/usr/bin/env bash
set -e

if [[ $1 = 1 ]]; then
  amixer -q sset Master toggle
elif [[ $1 = 2 ]]; then
  amixer -q sset Master 5-
elif [[ $1 = 3 ]]; then
  amixer -q sset Master 5+
fi

x=`amixer sget Master | tail -n 1 | tr -d "[]" | cut -d" " -f6 | tr -d "%"`
