#!/bin/bash
set -e

x=`pamixer --get-volume`

[ "$(pamixer --get-mute)" = "true" ] && printf "ﱝ\\n" && exit

if [ $x -gt "40" ]; then
	icon="墳"
elif [[ $x -lt "10" ]]; then
	icon="奄"
else
	icon="奔"
fi

echo "$icon $x%"
