#!/usr/bin/env bash

vol=`pulsemixer --get-volume | awk '{print $1}'`
[ "$(pulsemixer --get-mute)" = "1" ] && printf "ﱝ\\n" && exit

if [[ $vol -gt 60 ]]; then
  icon=""
elif [[ $vol -gt 20 ]]; then
  icon=""
else
  icon=""
fi
echo -e "$icon $vol%"
