#!/bin/bash

count=`ls ~/Pictures/Wallpapers | wc -l`
while [[ true ]]; do
  feh --bg-fill ~/Pictures/Wallpapers/$(ls ~/Pictures/Wallpapers/ | cat -n | grep -w `shuf -i 1-$count -n 1` | awk '{print $2}')
  sleep 300
done
