#!/usr/bin/env bash
ch=`printf "Search\\nToplist\\nDownloaded" | dmenu -p "Chose"`

if [[ $ch = "Search" ]]; then
  ch1=`echo | dmenu -p "Search"`
  ch1="`echo $ch1 | sed 's/ /+/g'`"
  if [[ $ch1 = "" ]]; then
    exit
  else
    wget -qO ~/.cache/wal_site https://alpha.wallhaven.cc/search?q=$ch1
  fi
elif [[ $ch1 == "Toplist" ]]; then
  wget -qO ~/.cache/wal_site https://alpha.wallhaven.cc/toplist
else
  sxiv -ft ~/Pictures
  exit
fi

grep -Po '(?<=href=")[^"]*' ~/.cache/wal_site | grep ".cc/wal" | grep -v "thu\|fav" | grep -o "......$" > ~/.cache/wal_list

for i in `cat ~/.cache/wal_list` ; do
  wget -qP ~/Pictures/AutoWall/ https://wallpapers.wallhaven.cc/wallpapers/full/wallhaven-$i.jpg
  wget -qP ~/Pictures/AutoWall/ https://wallpapers.wallhaven.cc/wallpapers/full/wallhaven-$i.png
  notify-send "Downloading..."
done

sxiv -ft ~/Pictures/AutoWall

notify-send "Downloaded"

rm -rf ~/Pictures/AutoWall/*
rm ~/.cache/wal_list ~/.cache/wal_site
